useAfterDeathHolograms: true
portal:
  world: world
  location: 0 60 0
score:
  per-kill: 8
  per-wrong-kill: -15
  per-death: -5
  per-30-sec-alive: 5
  per-gold-pickup: 1
  per-win: 10
stats:
  enabled: false
  host: localhost
  port: 3306
  user: minecraft
  pass: password
  name: minecraft
game:
  hologram: true
  visibleForOtherPlayers: true
  otherPlayersVisible: true
  minimumPlayersForStart: 6
  startCounter: 60
  goldSpawnInterval: 25
  giveSwordToMurderer: 10
  givePlayerLocator: 210
  detectiveBowReload: 6
  gameLength: 300
